### ISSUE TITLE
1.5차 AdSense 광고달기 

### ISSUE THREAD

**Issue by HyundeokPark** [get-rich-quick-attitude/get-rich-quick-attitude#50]
## 배경
에드센스 승인으로 에드센스 최적화 작업 필요
## TODO
- [x] #51
- [ ] #49 
- [x] #52
- [ ] #53
- [x] #54
- [x] #55

## 추가
- [ ] 에드센스 최적화

**Comment by rhsok** [comment]
투더제이 ibwj@piirra.com
본인소개, 창작물에 대한 소개, 개발 동기, 개발 환경정도의 설명을 약간 포함

**Comment by HyundeokPark** [comment]
광고 설정은 완료
