### ISSUE TITLE
에드센스 적용

### ISSUE THREAD

**Issue by HyundeokPark** [get-rich-quick-attitude/get-rich-quick-attitude#55]

**Comment by HyundeokPark** [comment]
![image](https://user-images.githubusercontent.com/12470341/210046706-b8540cfa-a5df-4a61-9414-22651a2588a4.png)

안나올때도 있는데, 왜 그런건지는 잘 모르겠음

**Comment by rhsok** [comment]
그래도 잘 뜨는듯?
오늘부터 공부할 때 써봐야지 ㅋㅋ

**Comment by HyundeokPark** [comment]
@rhsok 
개발자 도구 열어보면 에드센스 호출 api가 제대로 응답 안할때까 있는데, 넷틀리파이 자체적인 문제인지, 아니면 구글 에드센스 서버 문제인지는 확실치 않으나, 호출api가 제대로 안나올때면 나오지 않았다!...
