### ISSUE TITLE
타이머 앱 교체

### ISSUE THREAD

**Issue by HyundeokPark** [get-rich-quick-attitude/get-rich-quick-attitude#77]
[키워드 스프레드시트 정리본](https://docs.google.com/spreadsheets/d/1Hp4j8GtC9qnPlY0YcQHmV3deh02C7lCrfmxz5FP3EZQ/edit?usp=sharing)

_Originally posted by @HyundeokPark in https://github.com/get-rich-quick-attitude/get-rich-quick-attitude/issues/73#issuecomment-1400081833_
            

키워드 조사결과, 뽀모도로 쪽으로 가는것 보다, 일반적인 타이머 형식이 났다고 판단, 기존 앱의 디자인을 변경하는 쪽으로 생각중

**Comment by HyundeokPark** [comment]
[신규 타이머 후](https://codepen.io/s-coleman/pen/dRdZpm)

**Comment by rhsok** [comment]
css만 바꾸는 것 인가요?
동작 원리는 같아서 바꾸는 것은 크게 어렵지는 않지만 리팩토링 이후에 가능할 것 같습니다.

또한
여전히 react mpa 문제는 남아있는 것 같습니다.

CRA(create-react-app)으로 MPA구현이 가능한가에 대한 의문점이 입니다.

codepen에서 가져온 포모도로 코드는 CRA로 구현된 코드가 아닌 것 같습니다. 

여기에 대해서는 같이 알아보는 것이 좋을 것 같습니다.
[리액트 작동원리](https://velog.io/@juno7803/React%EA%B0%80-%ED%83%9C%EC%96%B4%EB%82%9C-%EB%B0%B0%EA%B2%BD)

**만약**

새로 만드는 것이면 바닐라 js로 mpa를 구현하는 것도 좋은 방법인 것 같습니다.

로직은 같으니 시간이 오래 걸리지 않습니다.

아니면 react로 spa 하되 seo를 최적화할 수 있는 방향으로 가야할 것 같습니다. 다양한 방법에 대해서는 노션에 정리할 예정입니다.

[](https://velog.io/@mujaen/React%EC%97%90%EC%84%9C-SEO-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0)

**Comment by HyundeokPark** [comment]
> css만 바꾸는 것 인가요? 동작 원리는 같아서 바꾸는 것은 크게 어렵지는 않지만 리팩토링 이후에 가능할 것 같습니다.
- CSS만 바꿔도 되지만, 앱 전체를 바꾸는게 훨씬 나을것 같습니다. CSS만 바꾸고 싶다면 의견주세여
> 
> 또한 여전히 react mpa 문제는 남아있는 것 같습니다.
> 
> CRA(create-react-app)으로 MPA구현이 가능한가에 대한 의문점이 입니다.
> 
- 해당 부분은 프로젝트에 크게 중요한 부분이 아닙니다. 반드시 리엑트로 개발할 필요가 없기 때문입니다.
> codepen에서 가져온 포모도로 코드는 CRA로 구현된 코드가 아닌 것 같습니다.
 - 코멘트에 쓰여있듯이 바닐라 자바스크립트로 구현된 코드가 맞습니다.
> 
> 현재 리팩토링된 코드는 CRA로 만들어져 있습니다.
> 
> 여기에 대해서는 같이 알아보는 것이 좋을 것 같습니다. [리액트 작동원리](https://velog.io/@juno7803/React%EA%B0%80-%ED%83%9C%EC%96%B4%EB%82%9C-%EB%B0%B0%EA%B2%BD)
> 
> **만약**
> 
> 새로 만드는 것이면 바닐라 js로 mpa를 구현하는 것도 좋은 방법인 것 같습니다.
> 
> 로직은 같으니 시간이 오래 걸리지 않습니다.
> 
> 아니면 react로 spa 하되 seo를 최적화할 수 있는 방향으로 가야할 것 같습니다. 다양한 방법에 대해서는 노션에 정리할 예정입니다.
