### ISSUE TITLE
Pomodoro React redux refactoring

### ISSUE THREAD

**Issue by rhsok** [get-rich-quick-attitude/get-rich-quick-attitude#78]
포모도로 타이머 & 휴식기능 완성

**추가 기능 예정**

1. 버튼을 바꾸는 효과를 넣을 것인가? pause-> resume / resume -> pause

2. 숫자를 클릭했을 때 숫자를 수정이 가능하게 구현

3.  리팩토링

4. 네비바 기능 및 css

5. 다국어지원 

6. 프리셋기능

**Comment by HyundeokPark** [comment]
같은 이슈를 여러개 생성하지말고, 하나의 이슈에서 해결합시다.
#39 확인하시고, 이 이슈는 닫아주세여
