### ISSUE TITLE
Onpage seo link 방법조사

### ISSUE THREAD

**Issue by rhsok** [get-rich-quick-attitude/get-rich-quick-attitude#87]
공통 html을 활용 할 수 있는지 조사하기.

**Comment by HyundeokPark** [comment]
## a태그(링크)로 페이지 이동하는 법
- [ ] 링크 당 HTML 파일  추가
  - 갈수록 유지하기 힘들뿐 더러, 다국어 지원 시 다국어 지원 수 만큼 페이지가 늘어난다.
  - 페이지가 늘어나면 로딩속도에도 영향을 미칠것이다.  
- [ ] 백엔드 서버 추가
   - 헤로쿠를 이용, 노드js나 java로 라우팅만 해주는 간단한 서버를 만든다.  
- [ ] netlify에서 지원하는 기능이 있는지 확인한다.
  - https://docs.netlify.com/routing/redirects/redirect-options/?_ga=2.72656602.81079057.1674910753-1404325249.1670726124#query-parameters

**Comment by HyundeokPark** [comment]
#88 a태그 만으로 값 수정은 가능하나, 이걸 onpage seo 링크로 볼 수 있을까?

**Comment by rhsok** [comment]
onpage로 볼 수 있을지 의문이 든다 -> 구글이 다른 콘텐츠로 인식 
백엔드가 있으면 같은 컨텐츠로 인식하나요?

**Comment by HyundeokPark** [comment]
> onpage로 볼 수 있을지 의문이 든다 -> 구글이 다른 콘텐츠로 인식 
백엔드가 있으면 같은 컨텐츠로 인식하나요?

백엔드를 추가해 서버 사이드 랜더링을 할 경우, html 파일은 같아도, 서버에서 이미 랜더링 되어 시간이나, 언어(쓰인 메타태그)등이 다르게 랜더링 될태니, 색인 시에 다른 컨텐츠로 볼거라고 생각합니다.

다른 URL에 같은 html파일이면 SEO에 좋지 않다는 글을 본것 같아, 같은 콘텐츠는 지양해야 할 것 같습니다. 만 
이 부분도 이참에 확실하게 확인하면 좋겠네요.

**Comment by HyundeokPark** [comment]
https://mygumi.tistory.com/385

**Comment by HyundeokPark** [comment]
정적인 script만으로는 불가, 기술도입으로 결정
